### ISSUE TITLE
Get Involved Link Connected to Events page

### ISSUE THREAD

**Issue by peterfiala** [enove/NoSLB#126]
when I enter in the address http://beta.wcasa.org/get-involved, it goes to the Events page but it shows 'Get Involved' underlined. When I enter in http://beta.wcasa.org/events, it goes to Get Involved. If I click on Events, the address shows http://beta.wcasa.org/events

**Comment by micchickenburger** [comment]
This issue is mostly resolved.  Because the scroll happens after a fixed period of time instead of after the entire page has completed rendering, it could still happen, but is now less likely since the location bar now only updates when most of a section is in the view port, instead of only when a section has reached the top of the viewport.

TODO:  Build a loading template.

**Comment by peterfiala** [comment]
Thanks!
