### ISSUE TITLE
Events: Switching months always goes to first event in that month

### ISSUE THREAD

**Issue by peterfiala** [enove/NoSLB#133]
When clicking the left arrow and going back to past events I noticed some events are skipped. When I then click on the right arrow, more events show up.

**Comment by micchickenburger** [comment]
Yes, this is intentional, but Eoghan and I have been discussing the strange appearance to users.  If there are no more events at the beginning of the month, click on the left arrow will go to the previous month; however, the first event in that month will become active.  It's not very intuitive.  I'm thinking loading three months at a time instead of just one will help the problem.

**Comment by peterfiala** [comment]
Whatever makes sense. Thanks!

Peter

Sent using OWA for iPhone
